#!/usr/bin/env python3
"""Publish approved personal drafts to Postiz.

Polls the content engine SQLite DB for approved drafts (sahil_twitter, sahil_linkedin),
finds associated images from article bundles or generated media, and queues them
into Postiz via the postiz_bridge. Postiz's Temporal workflow handles the actual
posting to X and LinkedIn at the scheduled time.

Runs as a no_agent cron job. Silent when nothing to publish.
"""
import os
import sys
import sqlite3
from pathlib import Path
from datetime import datetime, timezone, timedelta

# Set up paths
CE_DIR = Path(__file__).resolve().parent
DB_PATH = CE_DIR / "db" / "content_engine.db"
ARTICLE_OUTPUT = CE_DIR / "output" / "articles"

# Add CE dir to path for imports
sys.path.insert(0, str(CE_DIR))

from postiz_bridge import queue_post
from database import mark_published, get_draft

# Only publish personal accounts
ACTIVE_BRANDS = {"sahil_twitter", "sahil_linkedin"}

# Platform mapping: our platform name -> postiz_bridge platform key
PLATFORM_MAP = {
    "twitter": "twitter",
    "linkedin": "linkedin",
}


def find_article_image(draft_id: str, brand: str) -> str | None:
    """Find the hero image for an article draft from its bundle directory."""
    if not ARTICLE_OUTPUT.exists():
        return None

    # Article drafts have IDs starting with 'art_'
    # Check if there's a matching article bundle by looking at recent bundles
    for bundle_dir in sorted(ARTICLE_OUTPUT.iterdir(), reverse=True):
        if not bundle_dir.is_dir() or bundle_dir.name.startswith("_"):
            continue
        imgs_dir = bundle_dir / "imgs"
        if imgs_dir.exists():
            # Look for hero/infographic images (first image in the bundle)
            images = sorted(imgs_dir.glob("*.png")) + sorted(imgs_dir.glob("*.jpg")) + sorted(imgs_dir.glob("*.webp"))
            if images:
                # Return the first image (hero)
                return str(images[0])
        # Only check the most recent bundle
        break
    return None


def find_draft_image(draft: dict) -> str | None:
    """Find the best available image for a draft."""
    # 1. Check ai_image_path (generated by review-digest)
    ai_img = draft.get("ai_image_path")
    if ai_img and os.path.exists(ai_img):
        return ai_img

    # 2. Check visual_path (preview card image)
    vis_path = draft.get("visual_path")
    if vis_path and os.path.exists(vis_path):
        return vis_path

    # 3. For articles, check the article bundle directory
    content_type = draft.get("content_type", "")
    if content_type == "article":
        return find_article_image(draft.get("id", ""), draft.get("brand", ""))

    return None


def publish_approved_drafts() -> int:
    """Find approved personal drafts and queue them into Postiz.

    Returns the number of drafts published.
    """
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    c = conn.cursor()

    # Find approved personal drafts that haven't been published to Postiz yet
    c.execute(
        """SELECT id, brand, platform, body_text, title, content_type,
                  ai_image_path, visual_path, approved_at, pillar
           FROM drafts
           WHERE brand IN (?, ?)
             AND status = 'approved'
             AND postiz_id IS NULL
           ORDER BY approved_at ASC""",
        tuple(ACTIVE_BRANDS),
    )
    rows = c.fetchall()

    if not rows:
        conn.close()
        return 0

    published = 0
    for row in rows:
        draft = dict(row)
        draft_id = draft["id"]
        brand = draft["brand"]
        platform = draft["platform"]

        # Map platform to postiz bridge key
        bridge_platform = PLATFORM_MAP.get(platform, platform or "twitter")

        # Find associated image
        media_path = find_draft_image(draft)

        # For articles, strip markdown image syntax from body for social posting
        body = draft["body_text"]
        if draft["content_type"] == "article":
            # Articles go as text posts with the image attached separately
            # Remove markdown image syntax for the social post body
            import re
            body = re.sub(r'!\[.*?\]\(.*?\)', '', body).strip()
            # Truncate for platform
            if platform == "twitter":
                # X articles are long-form, but the post body should be a teaser
                # Take first paragraph + link placeholder
                first_para = body.split('\n\n')[0]
                if len(first_para) > 270:
                    first_para = first_para[:267] + "..."
                body = first_para
            elif platform == "linkedin":
                # LinkedIn: take first 2-3 paragraphs as the post body
                paragraphs = body.split('\n\n')[:3]
                body = '\n\n'.join(paragraphs)
                if len(body) > 2900:
                    body = body[:2897] + "..."

        # Schedule 2 hours from now if no specific time
        publish_at = datetime.now(timezone.utc) + timedelta(hours=2)

        try:
            postiz_id = queue_post(
                body_text=body,
                brand=brand,
                platform=bridge_platform,
                title=draft.get("title"),
                publish_at=publish_at,
                state="QUEUE",
                media_path=media_path,
            )

            if postiz_id:
                # Mark as published in content engine DB
                c.execute(
                    "UPDATE drafts SET status = 'published', published_at = ?, postiz_id = ? WHERE id = ?",
                    (datetime.now(timezone.utc).isoformat(), postiz_id, draft_id),
                )
                conn.commit()
                published += 1
                img_status = "with image" if media_path else "text-only"
                print(f"  Published: {draft_id} ({brand}/{platform}) {img_status} -> Postiz:{postiz_id[:8]}")
            else:
                print(f"  Failed: {draft_id} ({brand}/{platform}) — no integration or insert failed")

        except Exception as e:
            print(f"  Error publishing {draft_id}: {e}")

    conn.close()
    return published


if __name__ == "__main__":
    count = publish_approved_drafts()
    if count == 0:
        # Silent when nothing to publish
        pass
    else:
        print(f"Published {count} draft(s) to Postiz.")
