#!/usr/bin/env bash
# KENSEI GitOps — one-shot installer for ~/.hermes GitOps + auto-commit watcher.
# Idempotent: safe to re-run.
#
# What it does, in order:
#   1. Pre-flight: verify ~/.hermes exists, is not already a git repo
#   2. git init ~/.hermes with KENSEI author identity
#   3. Render .gitignore from the template
#   4. Install pre-commit hook (copies from scripts/gitops/pre-commit-lint.sh)
#   5. Deploy watcher + backfill scripts to ~/.hermes/scripts/gitops/
#   6. Install cron entry for the watcher (5 min debounce)
#   7. Initial commit of curated paths (config, profiles, cron, governance, scripts, skills, runbooks)
#   8. Smoke test: trigger a benign config edit, verify watcher commits within 6 min
#
# Usage:  bash scripts/gitops/install.sh
# Re-run: idempotent; safe to re-invoke.

set -euo pipefail

HERMES_HOME="${HERMES_HOME:-/home/kensei/.hermes}"
KENSEI_REPO="${KENSEI_REPO:-/home/kensei/repos/KenseiAgent}"
TEMPLATE="$KENSEI_REPO/scripts/gitops/templates/.gitignore.template"
WATCHER_SRC="$KENSEI_REPO/scripts/gitops/hermes-auto-commit.sh"
LINT_SRC="$KENSEI_REPO/scripts/gitops/pre-commit-lint.sh"
BACKFILL_SRC="$KENSEI_REPO/scripts/gitops/backfill-from-ledger.py"
DEPLOY_DIR="$HERMES_HOME/scripts/gitops"
HOOK_PATH="$HERMES_HOME/.git/hooks/pre-commit"
STATE_DIR="$DEPLOY_DIR/state"

log()  { printf '[%s] %s\n' "$(date -u +%FT%TZ)" "$*"; }
fail() { log "FAIL: $*" >&2; exit 1; }

# 1. Pre-flight.
[[ -d "$HERMES_HOME" ]] || fail "$HERMES_HOME does not exist"
if [[ -d "$HERMES_HOME/.git" ]]; then
  log "git repo already present at $HERMES_HOME/.git — skipping init (idempotent)"
else
  log "git init $HERMES_HOME"
  git init -q -b main "$HERMES_HOME"
fi

# Author identity (local; this is a private Tailscale-only repo).
git -C "$HERMES_HOME" config user.name  "KENSEI"
git -C "$HERMES_HOME" config user.email "kensei@local"
git -C "$HERMES_HOME" config commit.gpgsign false
git -C "$HERMES_HOME" config core.hooksPath "$HERMES_HOME/.git/hooks"

# 2. Render .gitignore.
if [[ ! -f "$HERMES_HOME/.gitignore" ]]; then
  [[ -f "$TEMPLATE" ]] || fail "template missing: $TEMPLATE"
  cp "$TEMPLATE" "$HERMES_HOME/.gitignore"
  log "wrote $HERMES_HOME/.gitignore"
else
  log ".gitignore already present — leaving as-is"
fi

# 3. Install pre-commit hook.
mkdir -p "$HERMES_HOME/.git/hooks"
if [[ -f "$LINT_SRC" ]]; then
  cp "$LINT_SRC" "$HOOK_PATH"
  chmod +x "$HOOK_PATH"
  log "installed pre-commit hook at $HOOK_PATH"
fi

# 4. Deploy watcher + backfill scripts.
mkdir -p "$STATE_DIR"
for src in "$WATCHER_SRC" "$BACKFILL_SRC"; do
  [[ -f "$src" ]] || fail "missing source: $src"
  # If the deploy dir is reached via a symlink (e.g. ~/.hermes/scripts →
  # ~/repos/KenseiAgent/scripts), the file is already in place. Detect with
  # `cmp -s` and skip the copy in that case.
  dst="$DEPLOY_DIR/$(basename "$src")"
  if cmp -s "$src" "$dst" 2>/dev/null; then
    log "deploy symlink-detected: $(basename "$src") already in place"
  else
    cp "$src" "$dst"
  fi
  chmod +x "$dst" 2>/dev/null || true
done
log "deployed watcher + backfill to $DEPLOY_DIR"

# 5. Install cron entry. Prefer a user crontab; fall back to a hint if crontab is locked.
CRON_LINE="*/5 * * * * $DEPLOY_DIR/hermes-auto-commit.sh >/dev/null 2>&1 # kensei-gitops-watcher"
if command -v crontab >/dev/null 2>&1; then
  CURRENT=$(crontab -l 2>/dev/null || true)
  if echo "$CURRENT" | grep -q "kensei-gitops-watcher"; then
    log "cron entry already present"
  else
    printf '%s\n%s\n' "$CURRENT" "$CRON_LINE" | crontab -
    log "installed cron: $CRON_LINE"
  fi
else
  log "crontab not available; install manually: $CRON_LINE"
fi

# 6. Initial commit of curated paths. Use the same path set as the watcher.
log "creating initial commit of curated paths"
cd "$HERMES_HOME"
git add -- config.yaml profiles cron governance scripts skills runbooks 2>/dev/null || true
if git diff --cached --quiet; then
  log "nothing to commit (curated paths already tracked or empty)"
else
  COMMIT_COUNT=$(git diff --cached --name-only | wc -l | tr -d ' ')
  git commit -q -m "init: GitOps for ~/.hermes

- ${COMMIT_COUNT} curated-path files tracked
- auto-commit watcher (5 min debounce) deployed
- pre-commit lint installed
- crontab entry installed
- .gitignore covers secrets, DBs, sessions, runtime state
- generated by scripts/gitops/install.sh"
  log "initial commit created (${COMMIT_COUNT} files)"
fi

# 7. Smoke test (lightweight): confirm the watcher runs without error.
log "smoke test: invoking watcher once"
if "$DEPLOY_DIR/hermes-auto-commit.sh"; then
  log "smoke test OK"
else
  log "smoke test exited non-zero (expected if nothing to commit) — continuing"
fi

log "install complete. Repo at: $HERMES_HOME"
log "view:  cd $HERMES_HOME && git log --oneline | head"
