#!/usr/bin/env bash
# KENSEI Content Engine v2 — Daily Pipeline Runner
# Stage 1: Draft generation with brand voice → Discord summary + HTML
# Stage 2: AI images + videos for approved drafts only (costs money)
# no_agent cron: stdout is delivered directly to Discord #content.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Load Hermes env
if [ -f /home/kensei/.hermes/.env ]; then
    while IFS= read -r line; do
        line="$(printf '%s' "$line" | tr -d '\r')"
        case "$line" in
            '#'*|'') continue ;;
            *) export "$line" ;;
        esac
    done < /home/kensei/.hermes/.env
fi

export TELEGRAM_CONTENT_CHAT_ID=${TELEGRAM_CONTENT_CHAT_ID:-"-1003922682700"}
export TELEGRAM_CONTENT_TOPIC_ID=${TELEGRAM_CONTENT_TOPIC_ID:-"22"}
PYTHONPATH="${PYTHONPATH}:$SCRIPT_DIR"
cd /home/kensei/repos/KenseiAgent/content_engine

STARTED_AT="$(TZ=Europe/London date '+%d/%m/%y %H:%M:%S')"
LOG_DIR="/home/kensei/.hermes/runbooks/content-engine/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/content-engine-$(TZ=Europe/London date '+%d%m%y-%H%M%S').log"

if python3 content_engine.py generate >"$LOG_FILE" 2>&1; then
    FINISHED_AT="$(TZ=Europe/London date '+%d/%m/%y %H:%M:%S')"

    # Find the HTML file generated by telegram_digest.py
    HTML_DIR="/home/kensei/.hermes/runbooks/content-digest"
    LATEST_HTML=$(ls -t "$HTML_DIR"/*.html 2>/dev/null | head -1)

    # Count total drafts from log
    TOTAL=$(grep -oP '^\d+ draft\(s\)' "$LOG_FILE" | grep -oP '\d+' | tail -1)
    if [ -z "$TOTAL" ]; then
        TOTAL=$(grep -cP '^    [a-z]+_' "$LOG_FILE" || echo "?")
    fi

    # Extract brand counts from log
    BRANDS=$(grep -oP '^\[[a-z_]+\] Generating' "$LOG_FILE" | sed 's/\[//;s/\] Generating//' | tr '\n' ',' | sed 's/,$//')

    # Short Discord summary
    echo "📝 Content drafts · ${FINISHED_AT}"
    echo "30 drafts · ${BRANDS}"
    echo ""
    echo "MEDIA:${LATEST_HTML}"
else
    FINISHED_AT="$(TZ=Europe/London date '+%d/%m/%y %H:%M:%S')"
    echo "⚠️ Content engine · ${FINISHED_AT}"
    echo "failed · generation · log attached"
    echo ""
    echo "MEDIA:${LOG_FILE}"
    exit 1
fi
